name = "DiscretePhasePortrait"
uuid = "8a3aab21-0cf5-4b1b-8a85-10b4e6308993"
authors = ["Allan R. Willms <awillms@uoguelph.ca> and HSI Wijerathna"]
version = "1.0.1"

[deps]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Contour = "0.6.3"
LinearAlgebra = "1.11.0"
Plots = "1.40.11"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
